SinoRPC/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

production/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.
class Line(models.Model):
	LineCode=models.CharField(max_length=10)

	def __str__(self):
		return self.LineCode

	class Meta:
		ordering=['-LineCode']

class Machine(models.Model):
	MachineCode=models.CharField(max_length=10)
	LineCode=models.ForeignKey('Line',on_delete=models.CASCADE,related_name="Machine",verbose_name = u'Line')

	def __str__(self):
		return self.MachineCode
	class Meta:
		ordering=['-MachineCode']

class Product(models.Model):
	ProductCode=models.CharField(max_length=20)
	MachineCode=models.ForeignKey('Machine',on_delete=models.CASCADE,related_name="Product",verbose_name = u'Machine',null = True, blank = True)
	ProductCT=models.CharField(max_length=20,default=1)

	def __str__(self):
		return self.ProductCode
	class Meta:
		ordering=['-ProductCode']

class Operation(models.Model):
	LineCode=models.ForeignKey('Line',null = True, blank = True,related_name="Operation",verbose_name = u'Line')
	MachineCode=models.ForeignKey('Machine',null = True, blank = True,related_name="Operation",verbose_name = u'Machine')
	ProductCode = models.ForeignKey('Product', null = True, blank = True,related_name="Operation",verbose_name = u'Product')
	DateTime=models.DateTimeField(auto_now_add=False, blank=True) 
	Consum=models.CharField(max_length=20)
	Good=models.CharField(max_length=20)
	Scraps=models.CharField(max_length=20)
	Duration=models.CharField(max_length=20)
	DownTime=models.CharField(max_length=20,null = True, blank = True,)

	class Meta:
		ordering=['-DateTime']

#creat ModelForm
class OperationForm(ModelForm):
	class Meta:
		model=Operation
		#fields='__all__'
		fields=('LineCode', 'MachineCode', 'ProductCode')


production/views.py
from django.shortcuts import render,render_to_response
from django.conf import settings
from django.http import JsonResponse

# Create your views here.
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from .import_data import import_data
from .models import *
from django.views.decorators.csrf import csrf_exempt
from registration.forms import RegistrationForm
def index(request):
    if request.method == 'POST':  
        form =OperationForm(request.POST) 
        if form.is_valid():
            return HttpResponseRedirect('/')
    else:  
        form =OperationForm()  
    return render_to_response('production/index.html',locals()) 
# upload file function
def upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        import_data(filename)
        return render(request, 'production/upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'production/upload.html')

@csrf_exempt
def cal(request):
    if request.method=='POST':
        form = OperationForm(request.POST)
        if form.is_valid():
            Line = form.cleaned_data['LineCode']
            Machine = form.cleaned_data['MachineCode']
            StartTime = form.cleaned_data['StartTime']
            EndTime = form.cleaned_data['EndTime']
            result=OEEcal(Line,Machine,StartTime,EndTime)
        else:
            form =OperationForm()
            result=''
    return render(request, 'production/index.html',locals())

def OEEcal(Line,Machine,StartTime,EndTime):
    Lines=Operation.objects.filter(LineCode__LineCode=Line,MachineCode__MachineCode=Machine,StartTime__gte=StartTime,EndTime__lte=EndTime)
    result=[]
    Output=0
    HU=0
    OAD=0
    OCT=int(Lines[1].ProductCode.ProductCT)
    for i in Lines:
        Output+=int(i.Good)
        HU+=int(i.Duration)
        OAD+=int(i.DownTime)
    OEE=Output*OCT/(HU+OAD)/3600
    return OEE
#############################################################
#send data to JS
def getLineCode(request):
    Lines = Line.objects.order_by('LineCode')
    res = []
    for i in Lines:
        res.append( [i.id, i.LineCode] )
    return JsonResponse({'LineCodes':res},safe=False)

def getMachineCode(request):
    Line = request.GET.get('LineCode')
    Machines= Machine.objects.filter(LineCode__LineCode__contains=Line).order_by('MachineCode')
    res = []
    for i in Machines:
        res.append([i.id, i.MachineCode])
    return JsonResponse({'MachineCodes':res},safe=False)

def getDateTime(request):
    Machine=request.GET.get('MachineCode')
    DateTimes= Operation.objects.filter(MachineCode__MachineCode__contains=Machine).order_by('-StartTime','-EndTime')
    res1=[]
    res2=[]
    for i in DateTimes:
        res1.append([i.id, i.StartTime])
        res2.append([i.id, i.EndTime])
    return JsonResponse({'StartTimes': res1,'EndTimes': res2},safe=False)


production/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SinoRPC</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "highchart/code/css/highcharts.css" %}" rel="stylesheet">
    <!-- Custom CSS -->
	<!--     <link href="{% static "css/heroic-features.css" %}" rel="stylesheet"> -->
	    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
	<style type="text/css">
		body{  
		  min-height: 100%;//最底高度为页面的100%高度

		}
		footer{
			position:absolute;  
			bottom: 0;  
			width: 100%;  
			clear: both;//清除浮动  
			line-height: 30px;   
			}
		.tophead{
			height: 65px;
			width: 100%;
			position: fixed;
			top: 0;
		}
		.main{
			width: 100%;
			position: fixed;
			top: 80px;
		}  
	</style>
</head>
<body>
	<div align="center" class="tophead" style="background-color: #4682B4; color:white"><h3>Welcome to SinoRPC</h3></div><p></p>
	<div class="row ">{% block title %}{% endblock %}</div>
	<div class="row main" style="">{% block content %}{% endblock %}</div>
	<!-- Js -->
	    <script src="{% static "js/jquery.js" %}"></script>
	    <!-- Bootstrap Core JavaScript -->
	    <script src="{% static "js/bootstrap.min.js" %}"></script>
	    <!-- Highcharts -->
	    <script src="{% static "highchart/code/js/highcharts.js" %}"></script>
	<footer>
		<div align="center" style="background-color: #4682B4;">
			<hr>&copy; Copyright 2018 ShiMenIT
		</div>

	</footer>
</body>
</html>

production/templates/production/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div align="left" class="col-md-6 col-md-offset-3" style="background-color:#B0C4DE">
	<h4 align="center"><b>You can query the data here</b></h4>
	<hr>
	<form action="{% url 'cal' %}" method="post">{% csrf_token %} 
		{{ form.errors }} 
	   	{{ form.as_p}}
<!-- 	   	{% for field in form %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
	    {% endfor %} -->
	<hr>
	<input type="submit" value="Submit">
	</form>	
</div>
<div class="well col-md-6 col-md-offset-3">
	{{ result}}
</div>
<p></p>
<div align="center" class="col-md-6 col-md-offset-3">
	<h5>You can upload your data in csv format here <a href="{% url 'upload' %}">upload</a></h5>
</div>

<!-- Js part -->
<script type="text/javascript">
	$(function(){
		//get line
		$("#id_LineCode").empty().append('<option value="">Choose Line</option>');
		$("#id_MachineCode").empty().append('<option value="">Choose Machine</option>');
		$("#id_StartTime").empty().append('<option value="">Choose StartTime</option>');
		$("#id_EndTime").empty().append('<option value="">Choose EndTime</option>');
		$.get('/getLineCode/',function(data){
		for(var i=0,len=data.LineCodes.length;i<len ;i++){
		    $new = $("<option value="+data.LineCodes[i][1] +">"+data.LineCodes[i][1]  +"</option>" );
		    $("#id_LineCode").append( $new );
		}
		});
		//after change line
		$("#id_LineCode").change(function(){
			$("#id_MachineCode").empty().append('<option value="">Choose Machine</option>');
			$("#id_StartTime").empty().append('<option value="">Choose StartTime</option>');
			$("#id_EndTime").empty().append('<option value="">Choose EndTime</option>');
			$.ajax({
			    url:'/getMachineCode/',
			    type:'get',
			    data:{"LineCode":$(this).val()}
			}).done(function(data){
			    for(var i = 0,len = data.MachineCodes.length; i<len ;i++){
			        $new = $( "<option value="+data.MachineCodes[i][1] +">"+data.MachineCodes[i][1]  +"</option>" );
			        $("#id_MachineCode").append( $new );
			    }
			});
		});
		//after change machine
		$("#id_MachineCode").change(function(){
			$("#id_StartTime").empty().append('<option value="">Choose StartTime</option>');
			$("#id_EndTime").empty().append('<option value="">Choose EndTime</option>');
			$.ajax({
			    url:'/getDateTime/',
			    type:'get',
			    data:{"MachineCode":$(this).val()}
			}).done(function(data){
			    for(var i = 0,len = data.StartTimes.length; i<len ;i++){
			        $new = $( "<option value="+data.StartTimes[i][1] +">"+ data.StartTimes[i][1]+"</option>" );
			        $("#id_StartTime").append($new );
			    }
			    for(var i = 0,len = data.EndTimes.length; i<len ;i++){
			        $new = $( "<option value="+data.EndTimes[i][1] +">"+ data.EndTimes[i][1]+"</option>" );
			        $("#id_EndTime").append($new );
			    }
			});
		});

		})
</script>

{% endblock %}

production/templates/production/table.html
{% block content %}  
<h1>修改资料</h1>  
{% if form.errors %}  
<p class="errors">请修改下面的错误: {{ form.non_field_errors }}</p>  
{% endif %}  
<form method="post" action="" enctype="multipart/form-data">  
<table>  
    {{form}}  
</table>  
{%load trade_tags%}  
{{cascade_select_list|cascade_select}}  
<p class="submit"><input type="submit" value="修改"></p>  
</form>  
{% endblock %} 

production/templates/production/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data" action="{% url 'upload' %}">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

	<p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}